<a href="https://colab.research.google.com/github/ykitaguchi77/statistics_for_articles/blob/main/CASIA_Refractive_map.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**CASIA_refractive_map**

CASIA2よりDLしたcsvからrefractive mapの部分を抜き出し

In [2]:
# prompt: gdrive

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
parent_dir = "/content/drive/Shareddrives/岩崎Dr_IgG4 deulk/眼瞼下垂/CASIAデータ/上皮"
csv_dir = "/content/drive/Shareddrives/岩崎Dr_IgG4 deulk/眼瞼下垂/CASIAデータ/上皮/01932018_20191211_111300_CASIA2_R_002_MAP(Data).csv"

In [4]:
# CSVの形が特殊なので1行ずつ開く。


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import csv

def extract_refractive_data_to_df(file_path):
    # セクションの開始行と終了行を探す
    section_start = None
    data_start = None
    section_end = None

    with open(file_path, 'r', encoding='utf-8', errors='replace') as file:
        lines = file.readlines()

        for i, line in enumerate(lines):
            if '[Refractive Keratometric]' in line:
                section_start = i
            elif section_start is not None and 'Data' in line and data_start is None:
                data_start = i + 1  # Dataの次の行からデータ開始
            elif section_start is not None and data_start is not None and line.strip() and line.strip()[0] == '[':
                # 次のセクションの開始
                section_end = i
                break

    if section_start is None or data_start is None:
        print("必要なセクションが見つかりませんでした。")
        return None

    if section_end is None:
        section_end = len(lines)  # ファイルの終わりまで

    # データ行を抽出して処理
    data_rows = []
    for i in range(data_start, section_end):
        line = lines[i].strip()
        if not line:
            continue

        # CSVの行を処理
        row_values = []
        for value in line.split(','):
            value = value.strip()
            if value:
                try:
                    row_values.append(float(value))
                except ValueError:
                    # 数値に変換できない場合はスキップ
                    continue

        if row_values:
            data_rows.append(row_values)

    # すべての行が同じ長さになるように調整
    max_length = max(len(row) for row in data_rows) if data_rows else 0

    for i in range(len(data_rows)):
        if len(data_rows[i]) < max_length:
            # 不足している要素をNaNで埋める
            data_rows[i] = data_rows[i] + [np.nan] * (max_length - len(data_rows[i]))

    # DataFrameに変換
    df = pd.DataFrame(data_rows)

    return df

# ファイルパス
csv_dir = "/content/drive/Shareddrives/岩崎Dr_IgG4 deulk/眼瞼下垂/CASIAデータ/上皮/01932018_20191211_111300_CASIA2_R_002_MAP(Data).csv"

# データを抽出してDataFrameに変換
df = extract_refractive_data_to_df(csv_dir)
df

,0,1,2,3,4,5,6,7,8,9,...,390,391,392,393,394,395,396,397,398,399
0,42.67,42.66,42.66,42.66,42.66,42.66,42.67,42.69,42.70,42.72,...,20.53,20.45,20.39,20.33,20.28,20.23,20.19,20.15,20.13,20.10
1,42.78,42.77,42.76,42.75,42.75,42.75,42.76,42.77,42.78,42.79,...,20.79,20.74,20.70,20.66,20.63,20.60,20.59,20.57,20.57,20.57
2,42.94,42.93,42.92,42.91,42.90,42.90,42.90,42.91,42.91,42.92,...,22.19,22.16,22.13,22.10,22.08,22.07,22.06,22.05,22.05,22.05
3,43.12,43.10,43.09,43.08,43.07,43.07,43.07,43.07,43.07,43.07,...,23.25,23.24,23.23,23.22,23.21,23.21,23.20,23.21,23.21,23.22
4,43.34,43.32,43.31,43.30,43.29,43.28,43.28,43.27,43.27,43.27,...,26.19,26.22,26.25,26.28,26.30,26.32,26.34,26.36,26.38,26.39
5,43.50,43.49,43.48,43.47,43.47,43.46,43.46,43.47,43.47,43.47,...,23.26,23.24,23.22,23.21,23.19,23.19,23.18,23.18,23.19,23.19
6,43.55,43.54,43.54,43.54,43.54,43.54,43.55,43.55,43.56,43.57,...,24.19,24.17,24.15,24.14,24.12,24.12,24.11,24.11,24.12,24.12
7,43.50,43.49,43.49,43.49,43.50,43.50,43.51,43.52,43.53,43.55,...,26.77,26.78,26.78,26.79,26.80,26.81,26.82,26.83,26.84,26.86
8,43.34,43.34,43.34,43.34,43.34,43.34,43.35,43.36,43.37,43.38,...,27.78,27.77,27.76,27.76,27.76,27.77,27.77,27.78,27.79,27.81
9,43.09,43.09,43.10,43.10,43.11,43.11,43.12,43.13,43.14,43.16,...,30.69,30.68,30.68,30.69,30.69,30.70,30.72,30.73,30.75,30.77
10,42.82,42.83,42.85,42.86,42.88,42.90,42.91,42.93,42.96,42.98,...,32.51,32.51,32.51,32.52,32.53,32.54,32.56,32.58,32.60,32.63
11,42.76,42.77,42.80,42.82,42.84,42.87,42.89,42.92,42.95,42.98,...,33.67,33.67,33.67,33.67,33.68,33.69,33.71,33.73,33.75,33.78
12,42.74,42.76,42.78,42.81,42.83,42.86,42.89,42.92,42.95,42.98,...,34.73,34.72,34.72,34.72,34.73,34.74,34.76,34.78,34.81,34.84
13,42.72,42.74,42.76,42.78,42.80,42.82,42.85,42.88,42.90,42.93,...,36.23,36.23,36.24,36.24,36.26,36.28,36.30,36.33,36.36,36.40
14,42.60,42.61,42.63,42.65,42.67,42.70,42.73,42.75,42.78,42.82,...,34.95,34.92,34.91,34.90,34.89,34.89,34.90,34.92,34.94,34.97
15,42.61,42.62,42.65,42.67,42.70,42.73,42.76,42.79,42.82,42.86,...,35.05,35.02,34.99,34.98,34.97,34.97,34.98,34.99,35.01,35.04
16,42.70,42.72,42.75,42.78,42.81,42.84,42.87,42.91,42.94,42.98,...,37.46,37.45,37.45,37.46,37.47,37.48,37.51,37.54,37.57,37.61
17,42.82,42.84,42.87,42.89,42.93,42.96,42.99,43.03,43.07,43.10,...,36.61,36.60,36.59,36.60,36.60,36.62,36.64,36.66,36.69,36.73
18,42.98,43.00,43.03,43.06,43.09,43.12,43.15,43.19,43.22,43.26,...,36.70,36.69,36.69,36.70,36.71,36.73,36.75,36.78,36.82,36.86
19,43.16,43.18,43.20,43.23,43.26,43.29,43.33,43.36,43.39,43.43,...,36.50,36.49,36.48,36.49,36.49,36.51,36.53,36.55,36.58,36.62
20,43.37,43.39,43.42,43.44,43.47,43.50,43.52,43.55,43.58,43.61,...,27.50,27.48,27.46,27.45,27.44,27.44,27.44,27.45,27.46,27.47
21,43.52,43.54,43.56,43.58,43.60,43.62,43.64,43.66,43.69,43.71,...,36.30,36.29,36.29,36.29,36.30,36.31,36.33,36.35,36.38,36.42
22,43.56,43.58,43.59,43.61,43.62,43.64,43.66,43.67,43.69,43.71,...,35.96,35.95,35.94,35.94,35.95,35.96,35.97,35.99,36.02,36.06
23,43.51,43.52,43.53,43.55,43.57,43.58,43.60,43.62,43.64,43.66,...,26.27,26.24,26.20,26.18,26.16,26.14,26.14,26.13,26.14,26.15
24,43.36,43.37,43.38,43.40,43.41,43.43,43.45,43.47,43.49,43.50,...,34.53,34.53,34.52,34.53,34.53,34.55,34.56,34.58,34.61,34.64
25,43.10,43.10,43.11,43.12,43.13,43.15,43.16,43.18,43.19,43.21,...,35.92,35.92,35.92,35.93,35.95,35.97,35.99,36.02,36.05,36.08
26,42.81,42.81,42.81,42.81,42.81,42.82,42.83,42.84,42.85,42.86,...,29.83,29.80,29.78,29.77,29.76,29.75,29.76,29.76,29.78,29.80
27,42.73,42.72,42.71,42.71,42.71,42.71,42.71,42.72,42.73,42.74,...,25.23,25.21,25.20,25.18,25.17,25.16,25.15,25.15,25.14,25.14
28,42.71,42.70,42.69,42.68,42.68,42.68,42.68,42.69,42.69,42.70,...,9.99,9.92,9.85,9.78,9.72,9.66,9.60,9.54,9.48,9.42
29,42.70,42.69,42.68,42.68,42.68,42.69,42.69,42.70,42.71,42.72,...,11.07,10.97,10.88,10.79,10.71,10.62,10.54,10.46,10.39,10.31
30,42.58,42.57,42.57,42.57,42.58,42.59,42.60,42.61,42.63,42.64,...,18.38,18.28,18.19,18.11,18.04,17.97,17.91,17.85,17.81,17.77
31,42.58,42.58,42.58,42.58,42.59,42.59,42.61,42.62,42.64,42.66,...,17.86,17.73,17.60,17.47,17.35,17.24,17.13,17.02,16.92,16.82

In [5]:
#--- サマリー用 DataFrame ------------------------------------------------------
columns = ['Sec(0,0)', 'Sec(1,0)', 'Sec(1,1)', 'Sec(1,2)', 'Sec(1,3)', 'Sec(1,4)', 'Sec(1,5)', 'Sec(1,6)', 'Sec(1,7)',
           'Sec(2,0)', 'Sec(2,1)', 'Sec(2,2)', 'Sec(2,3)', 'Sec(2,4)', 'Sec(2,5)', 'Sec(2,6)', 'Sec(2,7)',
           'Sec(3,0)', 'Sec(3,1)', 'Sec(3,2)', 'Sec(3,3)', 'Sec(3,4)', 'Sec(3,5)', 'Sec(3,6)', 'Sec(3,7)']
result_df = pd.DataFrame(columns=columns)
result_df.loc[0] = np.nan  # 全ての値をNaNで初期化

#--- セクション定義（Excel A210 起点でセル番地をコメント） ----------------------
sections = {
    #               行範囲 (0‑based, 末尾含まない)   開始列   列幅
    'Sec(0,0)': {'rows': [(0, 32)],                'start_col':  0, 'num_cols': 49},  # A210:AW241

    'Sec(1,0)': {'rows': [(0, 2), (30, 32)],       'start_col': 49, 'num_cols': 75},  # AX210:DT211, AX240:DT241
    'Sec(1,1)': {'rows': [(2, 6)],                 'start_col': 49, 'num_cols': 75},  # AX212:DT215
    'Sec(1,2)': {'rows': [(6, 10)],                'start_col': 49, 'num_cols': 75},  # AX216:DT219
    'Sec(1,3)': {'rows': [(10, 14)],               'start_col': 49, 'num_cols': 75},  # AX220:DT223
    'Sec(1,4)': {'rows': [(14, 18)],               'start_col': 49, 'num_cols': 75},  # AX224:DT227
    'Sec(1,5)': {'rows': [(18, 22)],               'start_col': 49, 'num_cols': 75},  # AX228:DT231
    'Sec(1,6)': {'rows': [(22, 26)],               'start_col': 49, 'num_cols': 75},  # AX232:DT235
    'Sec(1,7)': {'rows': [(26, 30)],               'start_col': 49, 'num_cols': 75},  # AX236:DT239

    'Sec(2,0)': {'rows': [(0, 2), (30, 32)],       'start_col':124, 'num_cols': 50},  # DU210:FR211, DU240:FR241
    'Sec(2,1)': {'rows': [(2, 6)],                 'start_col':124, 'num_cols': 50},  # DU212:FR215
    'Sec(2,2)': {'rows': [(6, 10)],                'start_col':124, 'num_cols': 50},  # DU216:FR219
    'Sec(2,3)': {'rows': [(10, 14)],               'start_col':124, 'num_cols': 50},  # DU220:FR223
    'Sec(2,4)': {'rows': [(14, 18)],               'start_col':124, 'num_cols': 50},  # DU224:FR227
    'Sec(2,5)': {'rows': [(18, 22)],               'start_col':124, 'num_cols': 50},  # DU228:FR231
    'Sec(2,6)': {'rows': [(22, 26)],               'start_col':124, 'num_cols': 50},  # DU232:FR235
    'Sec(2,7)': {'rows': [(26, 30)],               'start_col':124, 'num_cols': 50},  # DU236:FR239

    'Sec(3,0)': {'rows': [(0, 2), (30, 32)],       'start_col':174, 'num_cols': 75},  # FS210:IO211, FS240:IO241
    'Sec(3,1)': {'rows': [(2, 6)],                 'start_col':174, 'num_cols': 75},  # FS212:IO215
    'Sec(3,2)': {'rows': [(6, 10)],                'start_col':174, 'num_cols': 75},  # FS216:IO219
    'Sec(3,3)': {'rows': [(10, 14)],               'start_col':174, 'num_cols': 75},  # FS220:IO223
    'Sec(3,4)': {'rows': [(14, 18)],               'start_col':174, 'num_cols': 75},  # FS224:IO227
    'Sec(3,5)': {'rows': [(18, 22)],               'start_col':174, 'num_cols': 75},  # FS228:IO231
    'Sec(3,6)': {'rows': [(22, 26)],               'start_col':174, 'num_cols': 75},  # FS232:IO235
    'Sec(3,7)': {'rows': [(26, 30)],               'start_col':174, 'num_cols': 75},  # FS236:IO239
}

#--- 平均値計算 ---------------------------------------------------------------
if df is not None and not df.empty:
    for col_name, s in sections.items():
        start_c, end_c = s['start_col'], s['start_col'] + s['num_cols']
        vals = []
        for r0, r1 in s['rows']:
            sub = df.iloc[r0:r1, start_c:end_c]
            vals.extend(pd.to_numeric(sub.stack(), errors='coerce').dropna())
        if vals:
            result_df.loc[0, col_name] = np.mean(vals)

print(result_df)

    Sec(0,0)   Sec(1,0)  Sec(1,1)   Sec(1,2)  Sec(1,3)  Sec(1,4)   Sec(1,5)  \
0  43.337481  43.382333   43.6634  44.219533   44.7439   44.3009  44.802533

   Sec(1,6)   Sec(1,7)  Sec(2,0)  ...  Sec(2,6)  Sec(2,7)   Sec(3,0)  \
0   44.5806  43.499033   43.8543  ...   46.3818   44.9979  44.028333

   Sec(3,1)   Sec(3,2)   Sec(3,3)  Sec(3,4)   Sec(3,5)  Sec(3,6)   Sec(3,7)
0   45.4564  45.797533  46.451733   46.2393  46.741967    45.327  44.843133

[1 rows x 25 columns]

##**左右による補正**

In [16]:
import pandas as pd

# ------------------ 方向ごとの j インデックス ------------------
J_IDX = {
    "R": {"N":0, "SN":1, "S":2, "ST":3, "T":4, "IT":5, "I":6, "IN":7},
    "L": {"N":4, "SN":3, "S":2, "ST":1, "T":0, "IT":7, "I":6, "IN":5},
}

ORDER = ["N", "SN", "S", "ST", "T", "IT", "I", "IN"]        # 常にこの順

# ------------------ サマリー作成関数 ------------------
def build_zone_summary(raw_df: pd.DataFrame, side: str = "R") -> pd.DataFrame:
    """
    raw_df : Sec(i,j) を列にもつ 1 行 DataFrame（あなたの result_df）
    side   : "R" または "L"
    return : 指定フォーマットの 1 行 DataFrame
    """
    side = side.upper()
    if side not in ("R", "L"):
        raise ValueError("side must be 'R' or 'L'")

    # 出力カラム
    cols_out = (
        ['Sec(0-2mm)'] +
        [f'Sec(2-5mm)<{d}>'  for d in ORDER] +
        [f'Sec(5-7mm)<{d}>'  for d in ORDER] +
        [f'Sec(7-10mm)<{d}>' for d in ORDER]
    )
    out = pd.DataFrame(columns=cols_out, index=[0])

    # ------ 中心 ------
    out.loc[0, 'Sec(0-2mm)'] = raw_df.loc[0, 'Sec(0,0)']

    # ------ 各リング ------
    for ring, label in zip([1, 2, 3],
                           ['Sec(2-5mm)', 'Sec(5-7mm)', 'Sec(7-10mm)']):
        for d in ORDER:
            j = J_IDX[side][d]
            out.loc[0, f'{label}<{d}>'] = raw_df.loc[0, f'Sec({ring},{j})']

    return out

In [26]:
summary_R = build_zone_summary(result_df, side="R")  # 右眼
summary_L = build_zone_summary(result_df, side="L")  # 左眼
print(summary_R)

  filename side  Sec(0-2mm)  Sec(2-5mm)<N>  Sec(2-5mm)<SN>  Sec(2-5mm)<S>  \
0      NaN    R   43.337481      43.382333         43.6634      44.219533

   Sec(2-5mm)<ST>  Sec(2-5mm)<T>  Sec(2-5mm)<IT>  Sec(2-5mm)<I>  ...  \
0         44.7439        44.3009       44.802533        44.5806  ...

   Sec(5-7mm)<I>  Sec(5-7mm)<IN>  Sec(7-10mm)<N>  Sec(7-10mm)<SN>  \
0        46.3818         44.9979       44.028333          45.4564

   Sec(7-10mm)<S>  Sec(7-10mm)<ST>  Sec(7-10mm)<T>  Sec(7-10mm)<IT>  \
0       45.797533        46.451733         46.2393        46.741967

   Sec(7-10mm)<I>  Sec(7-10mm)<IN>
0          45.327        44.843133

[1 rows x 27 columns]

#**複数ファイル一括処理**

In [24]:
import os
import pandas as pd
import numpy as np
from tqdm import tqdm

# --- CSV読込関数 ---
def extract_refractive_data_to_df(file_path):
    section_start = None
    data_start = None
    section_end = None

    with open(file_path, 'r', encoding='utf-8', errors='replace') as file:
        lines = file.readlines()

        for i, line in enumerate(lines):
            if '[Refractive Keratometric]' in line:
                section_start = i
            elif section_start is not None and 'Data' in line and data_start is None:
                data_start = i + 1
            elif section_start is not None and data_start is not None and line.strip() and line.strip()[0] == '[':
                section_end = i
                break

    if section_start is None or data_start is None:
        return None

    if section_end is None:
        section_end = len(lines)

    data_rows = []
    for i in range(data_start, section_end):
        line = lines[i].strip()
        if not line:
            continue
        row_values = []
        for value in line.split(','):
            value = value.strip()
            if value:
                try:
                    row_values.append(float(value))
                except ValueError:
                    continue
        if row_values:
            data_rows.append(row_values)

    max_length = max(len(row) for row in data_rows) if data_rows else 0
    for i in range(len(data_rows)):
        if len(data_rows[i]) < max_length:
            data_rows[i] += [np.nan] * (max_length - len(data_rows[i]))

    return pd.DataFrame(data_rows)

# --- セクション定義 ---
sections = {
    'Sec(0,0)': {'rows': [(0, 32)],                'start_col':  0, 'num_cols': 49},
    'Sec(1,0)': {'rows': [(0, 2), (30, 32)],       'start_col': 49, 'num_cols': 75},
    'Sec(1,1)': {'rows': [(2, 6)],                 'start_col': 49, 'num_cols': 75},
    'Sec(1,2)': {'rows': [(6, 10)],                'start_col': 49, 'num_cols': 75},
    'Sec(1,3)': {'rows': [(10, 14)],               'start_col': 49, 'num_cols': 75},
    'Sec(1,4)': {'rows': [(14, 18)],               'start_col': 49, 'num_cols': 75},
    'Sec(1,5)': {'rows': [(18, 22)],               'start_col': 49, 'num_cols': 75},
    'Sec(1,6)': {'rows': [(22, 26)],               'start_col': 49, 'num_cols': 75},
    'Sec(1,7)': {'rows': [(26, 30)],               'start_col': 49, 'num_cols': 75},
    'Sec(2,0)': {'rows': [(0, 2), (30, 32)],       'start_col':124, 'num_cols': 50},
    'Sec(2,1)': {'rows': [(2, 6)],                 'start_col':124, 'num_cols': 50},
    'Sec(2,2)': {'rows': [(6, 10)],                'start_col':124, 'num_cols': 50},
    'Sec(2,3)': {'rows': [(10, 14)],               'start_col':124, 'num_cols': 50},
    'Sec(2,4)': {'rows': [(14, 18)],               'start_col':124, 'num_cols': 50},
    'Sec(2,5)': {'rows': [(18, 22)],               'start_col':124, 'num_cols': 50},
    'Sec(2,6)': {'rows': [(22, 26)],               'start_col':124, 'num_cols': 50},
    'Sec(2,7)': {'rows': [(26, 30)],               'start_col':124, 'num_cols': 50},
    'Sec(3,0)': {'rows': [(0, 2), (30, 32)],       'start_col':174, 'num_cols': 75},
    'Sec(3,1)': {'rows': [(2, 6)],                 'start_col':174, 'num_cols': 75},
    'Sec(3,2)': {'rows': [(6, 10)],                'start_col':174, 'num_cols': 75},
    'Sec(3,3)': {'rows': [(10, 14)],               'start_col':174, 'num_cols': 75},
    'Sec(3,4)': {'rows': [(14, 18)],               'start_col':174, 'num_cols': 75},
    'Sec(3,5)': {'rows': [(18, 22)],               'start_col':174, 'num_cols': 75},
    'Sec(3,6)': {'rows': [(22, 26)],               'start_col':174, 'num_cols': 75},
    'Sec(3,7)': {'rows': [(26, 30)],               'start_col':174, 'num_cols': 75},
}

# --- 指定方向のインデックス ---
J_IDX = {
    "R": {"N":0, "SN":1, "S":2, "ST":3, "T":4, "IT":5, "I":6, "IN":7},
    "L": {"N":4, "SN":3, "S":2, "ST":1, "T":0, "IT":7, "I":6, "IN":5},
}
ORDER = ["N", "SN", "S", "ST", "T", "IT", "I", "IN"]

# --- ゾーン集約関数 ---
def build_zone_summary(raw_df: pd.DataFrame, side: str) -> pd.DataFrame:
    cols_out = (
        ['filename', 'side', 'Sec(0-2mm)'] +
        [f'Sec(2-5mm)<{d}>' for d in ORDER] +
        [f'Sec(5-7mm)<{d}>' for d in ORDER] +
        [f'Sec(7-10mm)<{d}>' for d in ORDER]
    )
    out = pd.DataFrame(columns=cols_out, index=[0])
    out['side'] = side

    out['Sec(0-2mm)'] = raw_df.loc[0, 'Sec(0,0)']
    for ring, label in zip([1, 2, 3], ['Sec(2-5mm)', 'Sec(5-7mm)', 'Sec(7-10mm)']):
        for d in ORDER:
            j = J_IDX[side][d]
            out[f'{label}<{d}>'] = raw_df.loc[0, f'Sec({ring},{j})']
    return out


def process_all_csvs_with_options(parent_dir, limit=None, output_path=None):
    summary_rows = []
    file_list = []

    # ファイル一覧の取得とフィルタリング
    for root, _, files in os.walk(parent_dir):
        for fname in files:
            if fname.lower().endswith(".csv") and "CASIA2_" in fname:
                file_list.append(os.path.join(root, fname))
    if limit is not None:
        file_list = file_list[:limit]

    # tqdmで進捗表示
    for fpath in tqdm(file_list, desc="Processing CSV files"):
        fname = os.path.basename(fpath)
        side_marker = fname.split("CASIA2_")[1][0]
        side = "R" if side_marker == "R" else "L"

        df_raw = extract_refractive_data_to_df(fpath)
        if df_raw is None:
            continue

        # 平均値計算
        result_df = pd.DataFrame(columns=[f'Sec({i},{j})' for i in range(4) for j in range(8)])
        result_df.loc[0] = np.nan
        for col_name, s in sections.items():
            start_c, end_c = s['start_col'], s['start_col'] + s['num_cols']
            vals = []
            for r0, r1 in s['rows']:
                sub = df_raw.iloc[r0:r1, start_c:end_c]
                vals.extend(pd.to_numeric(sub.stack(), errors='coerce').dropna())
            if vals:
                result_df.loc[0, col_name] = np.mean(vals)

        summary = build_zone_summary(result_df, side)
        summary['filename'] = fname
        summary_rows.append(summary)

    # 結合と保存
    final_df = pd.concat(summary_rows, ignore_index=True) if summary_rows else pd.DataFrame()
    if output_path:
        final_df.to_csv(output_path, index=False)

    return final_df

In [25]:
parent_dir = "/content/drive/Shareddrives/岩崎Dr_IgG4 deulk/眼瞼下垂/CASIAデータ/上皮"
summary_df = process_all_csvs_with_options(
    parent_dir,
    limit=None, #Noneにすれば全ファイルを処理
    output_path="/content/summary_output.csv"
)

Processing CSV files: 100%|██████████| 1/1 [00:00<00:00, 19.10it/s]